Add a missing block inside switch statement
Declaring variables inside switch statement requires a new block (at
least before the C23 extensions were introduced):

$ CC=clang meson build --werror -Dc_args=-Wno-deprecated-declarations
...
$ ninja -C build
ninja: Entering directory `build'
[24/84] Generating glib marshaller header src/polkitagent/polkitagentmarshal_h
INFO: Reading ../src/polkitagent/polkitagentmarshal.list...
[25/84] Generating glib marshaller source src/polkitagent/polkitagentmarshal_c
INFO: Reading ../src/polkitagent/polkitagentmarshal.list...
[53/84] Compiling C object src/polkitbackend/libpolkit-backend-1.a.p/polkitbackendactionpool.c.o
FAILED: src/polkitbackend/libpolkit-backend-1.a.p/polkitbackendactionpool.c.o
clang -Isrc/polkitbackend/libpolkit-backend-1.a.p -Isrc/polkitbackend -I../src/polkitbackend -I. -I.. -Isrc -I../src -Isrc/polkit -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/sysprof-6 -I/usr/include/gio-unix-2.0 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c99 -O2 -g -D_GNU_SOURCE -include config.h -Waggregate-return -Wdeclaration-after-statement -Wformat=2 -Wimplicit-function-declaration -Winit-self -Wmissing-declarations -Wmissing-include-dirs -Wmissing-prototypes -Wstrict-prototypes -Wno-format-y2k -Wno-declaration-after-statement -Wno-deprecated-declarations -fPIC -pthread -DWITH_GZFILEOP -D_POLKIT_COMPILATION -D_POLKIT_BACKEND_COMPILATION '-DPACKAGE_DATA_DIR="/usr/share"' '-DPACKAGE_SYSCONF_DIR="/etc"' -MD -MQ src/polkitbackend/libpolkit-backend-1.a.p/polkitbackendactionpool.c.o -MF src/polkitbackend/libpolkit-backend-1.a.p/polkitbackendactionpool.c.o.d -o src/polkitbackend/libpolkit-backend-1.a.p/polkitbackendactionpool.c.o -c ../src/polkitbackend/polkitbackendactionpool.c
../src/polkitbackend/polkitbackendactionpool.c:264:7: error: label followed by a declaration is a C23 extension [-Werror,-Wc23-extensions]
  264 |       const gchar **dir_names = (const gchar**) g_value_get_boxed (value);
      |       ^
1 error generated.

Follow-up for 9958c259f82b066f613d171d2934c1bd829e31a4.