ci: don't use sudo in Fedora containers
Since we're already root there.

This should fix the currently broken CIs failing with:

Run sudo dnf install -y dnf-plugins-core python3-dbusmock clang compiler-rt libasan libubsan
sudo: PAM account management error: Authentication service cannot retrieve authentication info
sudo: a password is required
Error: Process completed with exit code 1.